window.SEED_ART = [
    ["Mona Lisa","Leonardo da Vinci",
      "Never sold — French law forbids it. It was insured for $100 million for a 1962 U.S. tour, the highest art insurance value ever recorded at the time (roughly $1 billion today).",
      "High Renaissance. Painted 1503–1517 (about 14 years) — Leonardo worked on it on and off for the rest of his life, though most scholars think the core image was done by around 1506.",
      "It was stolen from the Louvre in 1911 by a former employee and stayed missing for two years before being recovered in Italy — the theft helped make it world-famous.",
      "April 15, 1452","Vinci, Republic of Florence","May 2, 1519","Amboise, France","B"],
    ["The Starry Night","Vincent Van Gogh",
      "Never sold — it's been part of MoMA's collection since 1941 and isn't for sale.",
      "Post-Impressionism. Painted within a single month, June 1889 (well under a year).",
      "Van Gogh painted it from memory, looking out the window of the asylum in Saint-Rémy-de-Provence where he had voluntarily admitted himself.",
      "March 30, 1853","Groot-Zundert, Netherlands","July 29, 1890","Auvers-sur-Oise, France","B"],
    ["Whistler's Mother","James McNeill Whistler",
      "Never sold at auction — the French state bought it directly from Whistler in 1891 for 4,000 francs, a modest sum, and it's stayed in French collections since.",
      "Realism / Aestheticism. Painted in 1871 (exact working time isn't documented, but likely a matter of weeks).",
      "Its real title is \"Arrangement in Grey and Black No. 1\" — Whistler meant it as a study in color and composition, not just a portrait of his mother.",
      "July 11, 1834","Lowell, Massachusetts, USA","July 17, 1903","London, England","B"],
    ["American Gothic","Grant Wood",
      "Never sold since 1930 — the Art Institute of Chicago acquired it that year after Wood won a $300 prize with it in a competition.",
      "American Regionalism. Painted in 1930 (a few months).",
      "The models weren't a married couple — they were Wood's sister and his dentist.",
      "February 13, 1891","Anamosa, Iowa, USA","February 12, 1942","Iowa City, Iowa, USA","B"],
    ["The Scream","Edvard Munch",
      "This pastel version sold at Sotheby's in 2012 for $119.9 million — at the time, the highest price ever paid for a work of art at auction.",
      "Symbolism / Expressionism. This pastel version was made in 1895 (a matter of days — Munch worked quickly on each version he made).",
      "Munch hand-painted a poem on the frame describing feeling \"the great scream in nature\" while walking at sunset — the moment that inspired the image.",
      "December 12, 1863","Løten, Norway","January 23, 1944","Oslo, Norway","B"],
    ["The Creation of Adam","Michelangelo",
      "Never sold — it's a fresco painted directly onto the Sistine Chapel ceiling in Vatican City, so it's physically impossible to sell.",
      "High Renaissance. Painted 1508–1512 (4 years).",
      "Michelangelo initially resisted the commission, insisting he was a sculptor, not a painter — and he worked mostly standing on scaffolding, not lying on his back as legend often claims.",
      "March 6, 1475","Caprese, Republic of Florence","February 18, 1564","Rome, Papal States","B"],
    ["The Persistence of Memory","Salvador Dalí",
      "Never sold — donated to MoMA in 1934 and has remained there since.",
      "Surrealism. Painted in 1931 — Dalí claimed the melting-clock idea and much of the execution came together in a single sitting, though the full canvas likely took a few weeks.",
      "Despite its fame, the canvas is tiny — only about 9.5 x 13 inches, roughly the size of a sheet of paper.",
      "May 11, 1904","Figueres, Spain","January 23, 1989","Figueres, Spain","B"],
    ["Girl with a Pearl Earring","Johannes Vermeer",
      "Never sold — housed at the Mauritshuis in The Hague; insured for over €200 million when it travels, but not for sale.",
      "Dutch Golden Age. Painted around 1665 (exact working time unknown, likely a few months given Vermeer's slow, meticulous technique).",
      "It's not a portrait of a real, named person — it's a \"tronie,\" a study of an imagined face, which is part of why it's nicknamed the \"Dutch Mona Lisa.\"",
      "Baptized October 31, 1632 (exact birth date unrecorded)","Delft, Dutch Republic","December 15, 1675","Delft, Dutch Republic","B"],
    ["The Birth of Venus","Sandro Botticelli",
      "Never sold — part of the Uffizi Gallery's collection since the 1800s, originally painted for the Medici family.",
      "Early Renaissance (Florentine). Painted around 1485 (likely well under a year).",
      "Venus stands on an unrealistically large scallop shell; historians believe her pose was modeled directly on ancient Greek and Roman sculptures of the goddess.",
      "c. March 1445","Florence, Republic of Florence","May 17, 1510","Florence, Republic of Florence","B"],
    ["The Night Watch","Rembrandt",
      "Never sold — owned by the city of Amsterdam and displayed at the Rijksmuseum since the 19th century.",
      "Dutch Golden Age / Baroque. Painted in 1642 (about a year, typical for a large group portrait commission of the time).",
      "The canvas was trimmed on all sides in 1715 to fit between two doors, permanently cutting off part of the scene — and it's been slashed by vandals more than once since.",
      "July 15, 1606","Leiden, Dutch Republic","October 4, 1669","Amsterdam, Dutch Republic","B"],
    ["The Kiss","Gustav Klimt",
      "Never sold — the Austrian state bought it directly from Klimt in 1908, and it's been at Vienna's Belvedere Museum ever since.",
      "Vienna Secession / Symbolism. Painted 1907–1908 (about 1 year).",
      "Klimt applied real gold leaf to the canvas, a technique inspired by Byzantine mosaics he saw on a trip to Italy.",
      "July 14, 1862","Baumgarten, near Vienna, Austria","February 6, 1918","Vienna, Austria","B"],
    ["The Garden of Earthly Delights","Hieronymus Bosch",
      "Never sold — in the Museo del Prado's collection in Madrid since the late 1500s.",
      "Northern Renaissance. Painted sometime between 1490 and 1510 — Bosch's exact working dates are unknown.",
      "It's a triptych of three connected panels showing Eden, earthly pleasure, and hell — crammed with hundreds of bizarre invented creatures scholars still debate the meaning of.",
      "c. 1450","'s-Hertogenbosch, Duchy of Brabant","August 9, 1516","'s-Hertogenbosch, Duchy of Brabant","B"],
    ["Les Demoiselles d'Avignon","Pablo Picasso",
      "Never sold at public auction — MoMA acquired it in a private sale in 1937.",
      "Proto-Cubism. Painted in 1907 (several months, after many preparatory studies).",
      "Picasso considered it so radical he kept it mostly hidden in his studio for years — it's now seen as one of the paintings that launched Cubism.",
      "October 25, 1881","Málaga, Spain","April 8, 1973","Mougins, France","B"],
    ["The Last Supper","Leonardo da Vinci",
      "Never sold — it's a mural painted directly on a refectory wall in Milan, so it can't be moved or sold.",
      "High Renaissance. Painted 1495–1498 (3 years).",
      "Da Vinci used an experimental paint technique instead of true fresco, so the image began flaking within his own lifetime — it remains extremely fragile despite many restorations.",
      "April 15, 1452","Vinci, Republic of Florence","May 2, 1519","Amboise, France","B"],
    ["The Raft of the Medusa","Théodore Géricault",
      "Never sold — acquired by the Louvre shortly after Géricault's death and has remained there.",
      "Romanticism. Painted 1818–1819 (about 8 months, under a year).",
      "It depicts a real shipwreck disaster; Géricault studied corpses in morgues and hospitals so he could paint the dying survivors as accurately as possible.",
      "September 26, 1791","Rouen, France","January 26, 1824","Paris, France","B"],
    ["The School of Athens","Raphael",
      "Never sold — a fresco painted directly on a wall inside the Vatican's Apostolic Palace.",
      "High Renaissance. Painted 1509–1511 (about 2 years).",
      "Raphael gave many ancient philosophers the faces of his contemporaries — the figure of Plato is widely believed to be a portrait of Leonardo da Vinci.",
      "c. April 6, 1483","Urbino, Italy","April 6, 1520","Rome, Papal States","I"],
    ["The Girl with a Balloon","Banksy",
      "Sold at Sotheby's in 2018 for about £1.04 million ($1.4M) — then self-shredded through a hidden mechanism the instant the hammer fell. Retitled \"Love Is in the Bin,\" it resold in 2021 for £18.6 million ($25.4M), a record for the artist.",
      "Street Art / Contemporary. The stencil design dates to 2002; this canvas version was made in 2006 — street art pieces like this are typically made in hours, not months.",
      "Banksy had secretly built a paper shredder into the picture frame years earlier, in case the piece was ever auctioned — and it fired exactly as planned.",
      "Not publicly confirmed — identity remains anonymous","Believed to be Bristol, England","","","I"],
    ["The Great Wave off Kanagawa","Katsushika Hokusai",
      "As a woodblock print, thousands of copies were made — individual prints in good condition have sold at auction for over $1 million, but there's no single one-of-a-kind original to sell.",
      "Ukiyo-e (Japanese woodblock print). Designed around 1831, as part of a series produced over roughly a year.",
      "It's part of a series called \"Thirty-Six Views of Mount Fuji\" — the mountain itself is actually small and tucked in the background of the image.",
      "October 31, 1760","Edo (now Tokyo), Japan","May 10, 1849","Edo (now Tokyo), Japan","I"],
    ["Vase with Twelve Sunflowers","Vincent Van Gogh",
      "This version sold at Christie's in 1987 for £24.75 million ($39.9 million) to a Japanese insurance company — at the time, three times more than any artwork had ever sold for at auction.",
      "Post-Impressionism. Painted in 1888 (about a week — Van Gogh worked at a rapid pace).",
      "Van Gogh sold only one painting during his entire lifetime; he once wrote that he hoped to sell a Sunflowers canvas for the equivalent of about $125.",
      "March 30, 1853","Groot-Zundert, Netherlands","July 29, 1890","Auvers-sur-Oise, France","I"],
    ["Tableau I","Piet Mondrian",
      "No public sale record — it's held in a museum collection, not the private market.",
      "De Stijl / Neoplasticism. Painted around 1921 (exact duration undocumented, likely a matter of weeks).",
      "Mondrian limited himself to primary colors, black, white, and straight lines on purpose, believing this stripped-down style expressed pure, universal harmony.",
      "March 7, 1872","Amersfoort, Netherlands","February 1, 1944","New York City, USA","I"],
    ["Convergence","Jackson Pollock",
      "Never sold — donated to the Buffalo AKG Art Museum (then the Albright-Knox) in 1956 and has stayed in its collection since.",
      "Abstract Expressionism. Painted in 1952 (likely days to weeks — Pollock's drip technique was fast and physical).",
      "Pollock made it by dripping and flinging paint over a canvas laid flat on the floor, moving around and into the work itself instead of using a brush at an easel.",
      "January 28, 1912","Cody, Wyoming, USA","August 11, 1956","Springs, New York, USA","I"],
    ["Impression, Sunrise","Claude Monet",
      "Never sold — donated to the Musée Marmottan Monet in Paris in 1940 and has remained there.",
      "Impressionism. Painted in 1872, reportedly finished in a single sitting.",
      "A critic mocked the painting's loose, unfinished-looking brushwork in a review — and the word he used sarcastically, \"Impression,\" ended up naming the entire Impressionist movement.",
      "November 14, 1840","Paris, France","December 5, 1926","Giverny, France","I"],
    ["Woman with a Parasol — Madame Monet and Her Son","Claude Monet",
      "Never sold — gifted to the National Gallery of Art in Washington, D.C. in 1983.",
      "Impressionism. Painted in 1875, in a single outdoor session lasting a few hours.",
      "Monet painted it outdoors in a single session to catch the wind moving through the veil and grass — his wife Camille and son Jean were the models.",
      "November 14, 1840","Paris, France","December 5, 1926","Giverny, France","I"],
    ["Broadway Boogie Woogie","Piet Mondrian",
      "Never resold — MoMA bought it directly from Mondrian in 1943 for $800, shortly before his death.",
      "De Stijl / Neoplasticism (late, transitional style). Painted 1942–1943 (about 1 year).",
      "It was Mondrian's last finished painting, made after he moved to New York — the city's street grid and the rhythm of jazz inspired him to break his usual black grid lines into flickering colored squares.",
      "March 7, 1872","Amersfoort, Netherlands","February 1, 1944","New York City, USA","I"],
    ["Composition VII","Wassily Kandinsky",
      "Never sold — held by Moscow's State Tretyakov Gallery since the Soviet era.",
      "Expressionism (abstract). Painted in 1913 — after more than 30 preparatory studies, the final canvas itself took just 4 days.",
      "Kandinsky made over 30 sketches and studies before completing the final canvas in just four days — he considered it the most complex painting he ever made.",
      "December 16, 1866","Moscow, Russia","December 13, 1944","Neuilly-sur-Seine, France","I"],
    ["Irises","Vincent Van Gogh",
      "Sold at Sotheby's in 1987 for $53.9 million, a record at the time; it later moved to the J. Paul Getty Museum in a private sale.",
      "Post-Impressionism. Painted in 1889 (about a week, during Van Gogh's first week at the Saint-Rémy asylum).",
      "Van Gogh painted it during his first week at the Saint-Rémy asylum, working from the garden there rather than a scene of distress.",
      "March 30, 1853","Groot-Zundert, Netherlands","July 29, 1890","Auvers-sur-Oise, France","I"],
    ["Mother and Child","Mary Cassatt",
      "No confirmed public auction record for this specific work — Cassatt's mother-and-child paintings are held across several major U.S. museums.",
      "Impressionism. Painted in the early 1900s (exact working time for this specific canvas isn't documented).",
      "Cassatt was one of the few women — and the only American — to exhibit with the French Impressionists, and mothers with children became her signature subject.",
      "May 22, 1844","Allegheny City, Pennsylvania, USA","June 14, 1926","Le Mesnil-Théribus, France","I"],
    ["Flowers in a Crystal Vase","Édouard Manet",
      "No confirmed public auction record — held in a museum collection.",
      "Impressionism / Realism. Painted in the early 1880s (a small still life, likely just days).",
      "Illness made it hard for Manet to work on large canvases in his final years, so friends brought him fresh-cut flowers to paint in small still lifes like this one.",
      "January 23, 1832","Paris, France","April 30, 1883","Paris, France","I"],
    ["Young Hare","Albrecht Dürer",
      "Never sold — held by the Albertina museum in Vienna.",
      "Northern Renaissance. Painted in 1502 (likely several weeks, given its fine detail).",
      "It's watercolor and bodycolor on paper, and Dürer rendered every strand of fur so precisely that it's still studied today as a masterclass in observational drawing.",
      "May 21, 1471","Nuremberg, Holy Roman Empire","April 6, 1528","Nuremberg, Holy Roman Empire","I"],
    ["The Ancient of Days","William Blake",
      "Blake hand-colored each print himself, so no two copies are identical — individual copies have sold at auction, but there's no single original painting.",
      "Romanticism / Visionary art. Designed in 1794; Blake hand-colored copies individually for decades afterward, so any single copy's exact date varies.",
      "Blake considered it one of his finest works — he was reportedly still hand-coloring a copy of it in the days before he died in 1827.",
      "November 28, 1757","London, England","August 12, 1827","London, England","I"],
    ["Self-Portrait with Thorn Necklace and Hummingbird","Frida Kahlo",
      "Never sold — housed at the Harry Ransom Center at the University of Texas at Austin, part of a gift from photographer Nickolas Muray's collection.",
      "Surrealism / Mexican Modernism. Painted in 1940 (likely a few weeks).",
      "Kahlo painted it the year she divorced (and later remarried) muralist Diego Rivera — the thorn necklace is widely read as a symbol of her physical and emotional pain.",
      "July 6, 1907","Coyoacán, Mexico City, Mexico","July 13, 1954","Coyoacán, Mexico City, Mexico","N"],
    ["Three Musicians","Pablo Picasso",
      "Never sold — MoMA acquired its version in 1949; a second, nearly identical version is at the Philadelphia Museum of Art.",
      "Synthetic Cubism. Painted over the summer of 1921 (a few months).",
      "Picasso painted both large versions in the same summer — among the clearest examples of his Synthetic Cubist style.",
      "October 25, 1881","Málaga, Spain","April 8, 1973","Mougins, France","N"],
    ["A Sunday Afternoon on the Island of La Grande Jatte","Georges Seurat",
      "Never sold — bought by the Art Institute of Chicago in 1924 and has remained there since.",
      "Pointillism / Neo-Impressionism. Painted 1884–1886 (about 2 years).",
      "Seurat built the entire image from tiny dots of pure color, a technique called pointillism — up close it looks like static, but the dots blend into smooth color from a distance.",
      "December 2, 1859","Paris, France","March 29, 1891","Paris, France","N"],
    ["Guernica","Pablo Picasso",
      "Never for sale — Picasso refused to let it be shown in Spain while Franco was in power; it now belongs to the Spanish state at the Museo Reina Sofía.",
      "Cubism (with Surrealist influence). Painted in 1937, in about 35 days — well under two months.",
      "Picasso painted the huge canvas — over 11 feet tall and 25 feet wide — in about a month, reacting to the bombing of the Basque town of Guernica during the Spanish Civil War.",
      "October 25, 1881","Málaga, Spain","April 8, 1973","Mougins, France","N"],
    ["The Flower Carrier","Diego Rivera",
      "No confirmed public auction record — held at SFMOMA (San Francisco Museum of Modern Art).",
      "Mexican Muralism / Social Realism. Painted in 1935 (likely a few weeks).",
      "It shows a man straining to carry an enormous basket of flowers on his back while a woman helps hoist it, a recurring theme in Rivera's work about the physical labor of Mexican workers.",
      "December 8, 1886","Guanajuato, Mexico","November 24, 1957","Mexico City, Mexico","N"],
    ["Water Lilies, Giverny #4","Claude Monet",
      "Individual Water Lilies canvases have sold at auction for tens of millions of dollars — but Monet painted around 250 of them, so prices vary hugely by which canvas.",
      "Impressionism. This canvas dates from the early 1900s–1920s; Monet painted roughly 250 Water Lilies works over almost 30 years in total.",
      "Monet grew the water garden at his home in Giverny himself and painted it obsessively for nearly 30 years, even after cataracts badly damaged his eyesight.",
      "November 14, 1840","Paris, France","December 5, 1926","Giverny, France","N"],
    ["Café Terrace at Night","Vincent Van Gogh",
      "Never sold — held at the Kröller-Müller Museum in the Netherlands.",
      "Post-Impressionism. Painted in 1888, reportedly in a single overnight session.",
      "It's believed to be the first painting where Van Gogh used a starry night sky as the backdrop for a nighttime scene — and he painted it outdoors, at night, without using black paint anywhere in the sky.",
      "March 30, 1853","Groot-Zundert, Netherlands","July 29, 1890","Auvers-sur-Oise, France","N"],
    ["The Son of Man","René Magritte",
      "No confirmed public auction record for this specific painting, which is in a private collection; other versions and related Magritte self-portraits have sold for tens of millions of dollars.",
      "Surrealism. Painted in 1964 (likely a few weeks).",
      "Magritte said the floating apple hides the man's face on purpose: \"there is always something hidden by what we see,\" since we're naturally curious about what we can't see.",
      "November 21, 1898","Lessines, Belgium","August 15, 1967","Brussels, Belgium","N"],
    ["Bal du Moulin de la Galette","Pierre-Auguste Renoir",
      "A smaller version of this scene sold at Sotheby's in 1990 for $78.1 million; the large, famous version shown here is held at the Musée d'Orsay and has never been sold.",
      "Impressionism. Painted in 1876, over several months on location at a real dance hall.",
      "Renoir had friends pose as the dancers at a real open-air dance hall in Montmartre, carrying the large canvas back and forth each day to paint it on location.",
      "February 25, 1841","Limoges, France","December 3, 1919","Cagnes-sur-Mer, France","N"],
    ["Salvator Mundi","Leonardo da Vinci",
      "Sold at Christie's in 2017 for $450.3 million — the most expensive painting ever sold at auction, more than double the previous record.",
      "High Renaissance. Painted around 1500 (exact working time undocumented).",
      "It vanished from public record for centuries and was bought at a modest estate sale in 2005 for well under $10,000, before experts identified it as a genuine Leonardo.",
      "April 15, 1452","Vinci, Republic of Florence","May 2, 1519","Amboise, France","N"],
    ["Christina's World","Andrew Wyeth",
      "Never resold — MoMA's founding director bought it directly from the gallery in 1948 for just $1,800.",
      "American Realism / Magic Realism. Painted in 1948 (several months).",
      "The woman shown, Anna Christina Olson, had a condition that made walking difficult — but the body in the painting is a composite: Wyeth's wife Betsy actually posed for the torso.",
      "July 12, 1917","Chadds Ford, Pennsylvania, USA","January 16, 2009","Chadds Ford, Pennsylvania, USA","N"],
    ["The Painter of Sunflowers","Paul Gauguin",
      "No confirmed public auction record — held at the Van Gogh Museum in Amsterdam.",
      "Post-Impressionism. Painted in 1888 (a matter of days, during Gauguin's stay in Arles).",
      "It's Gauguin's portrait of Van Gogh painting sunflowers, made while the two briefly shared a house in Arles, France — their friendship famously ended in a violent argument weeks later.",
      "June 7, 1848","Paris, France","May 8, 1903","Atuona, Hiva Oa, French Polynesia","N"],
    ["Almond Blossom","Vincent Van Gogh",
      "Never sold — held at the Van Gogh Museum in Amsterdam.",
      "Post-Impressionism (Japonism-influenced). Painted in 1890 (about 2 weeks).",
      "Van Gogh painted it as a gift to celebrate the birth of his newborn nephew, who was named after him — one of the most hopeful paintings he made in his final months.",
      "March 30, 1853","Groot-Zundert, Netherlands","July 29, 1890","Auvers-sur-Oise, France","N"],
    ["The Sistine Chapel Ceiling","Michelangelo",
      "Never sold — it's a fresco built into the Vatican's Sistine Chapel, owned by the Holy See.",
      "High Renaissance. Painted 1508–1512 (4 years).",
      "The ceiling contains more than 300 figures across nine scenes from Genesis, and Michelangelo largely worked without assistants for the figures themselves.",
      "March 6, 1475","Caprese, Republic of Florence","February 18, 1564","Rome, Papal States","N"],
    ["The Arnolfini Portrait","Jan van Eyck",
      "Never sold since the National Gallery in London bought it in 1842.",
      "Northern Renaissance. Painted in 1434 (likely several months).",
      "A small convex mirror on the back wall reflects the entire room in miniature, including two extra figures not otherwise shown — one may be van Eyck himself.",
      "c. 1390","Maaseik, Prince-Bishopric of Liège","Before July 9, 1441","Bruges, Duchy of Burgundy","N"],
    ["Las Meninas","Diego Velázquez",
      "Never sold — part of the Spanish royal collection since it was painted, now at the Museo del Prado.",
      "Spanish Golden Age / Baroque. Painted in 1656 (exact duration undocumented, likely several months).",
      "Velázquez painted himself into the scene, brush in hand, and used a mirror in the background that reflects the king and queen — suggesting they're standing where the viewer is.",
      "June 6, 1599","Seville, Spain","August 6, 1660","Madrid, Spain","G"],
    ["Luncheon of the Boating Party","Pierre-Auguste Renoir",
      "Never resold since 1923, when American collector Duncan Phillips bought it for $125,000 — a huge sum for a painting at the time.",
      "Impressionism. Painted 1880–1881 (about a year).",
      "Nearly everyone in the painting was a real friend of Renoir's, including the woman in the straw hat playing with a dog in the foreground, who later became his wife.",
      "February 25, 1841","Limoges, France","December 3, 1919","Cagnes-sur-Mer, France","G"],
    ["Liberty Leading the People","Eugène Delacroix",
      "Never sold — bought by the French state shortly after it was painted; now at the Louvre.",
      "Romanticism. Painted in 1830, completed in about 3 months (September–December).",
      "It commemorates the July Revolution of 1830 — the bare-breasted figure of \"Liberty\" carrying the French flag is an allegorical figure, not a real participant.",
      "April 26, 1798","Charenton-Saint-Maurice, France","August 13, 1863","Paris, France","G"],
    ["Napoleon Crossing the Alps","Jacques-Louis David",
      "Never sold — David painted five versions for European royal collections, all of which remain in museums today.",
      "Neoclassicism. Painted 1801–1805 — David made five versions over 4 years; each individual version took a few months.",
      "Napoleon actually crossed the Alps on a mule, led by a guide, in calm weather — not rearing on a wild stallion in a storm as David dramatically imagined it.",
      "August 30, 1748","Paris, France","December 29, 1825","Brussels, Belgium","G"],
    ["Deposition of Christ","Caravaggio",
      "Never sold — held in the Vatican Museums' Pinacoteca.",
      "Baroque. Painted around 1602–1603 (about a year).",
      "Caravaggio was famous for using real people off the street as models for religious figures, and for his dramatic light-and-shadow technique, chiaroscuro, which influenced generations of painters.",
      "September 29, 1571","Milan, Italy","July 18, 1610","Porto Ercole, Tuscany","G"],
    ["The Sleeping Gypsy","Henri Rousseau",
      "Never resold since MoMA bought it in 1939, decades after Rousseau's death, for a relatively modest sum.",
      "Naïve Art / Primitivism. Painted in 1897 (weeks to months).",
      "Rousseau never traveled outside France and had no formal art training — a self-taught, part-time customs officer who painted the exotic scenes and animals purely from imagination and picture books.",
      "May 21, 1844","Laval, France","September 2, 1910","Paris, France","G"],
    ["Nighthawks","Edward Hopper",
      "Sold to the Art Institute of Chicago within months of being finished, in 1942, for $3,000.",
      "American Realism. Painted over about 6 weeks in the winter of 1941–1942 (well under a year).",
      "Hopper and his wife Jo posed for the figures themselves — he used a mirror to sketch his own face for the men at the counter, and Jo modeled for the red-haired woman.",
      "July 22, 1882","Nyack, New York, USA","May 15, 1967","New York City, USA","G"],
    ["Looking Down Yosemite Valley","Albert Bierstadt",
      "No confirmed public auction record — held in a museum collection.",
      "Hudson River School / Luminism. Painted in the 1860s, worked up in the studio from field sketches over several months.",
      "Bierstadt traveled with survey expeditions to the American West and often enlarged or combined real landscape features to make his paintings feel even grander than the actual scenery.",
      "January 7, 1830","Solingen, Germany","February 18, 1902","New York City, USA","G"],
    ["Birds of America","John James Audubon",
      "A complete first-edition set of Audubon's engravings sold at Sotheby's in 2010 for $11.5 million — at the time, the most expensive printed book ever sold at auction.",
      "Naturalism / Scientific illustration. The full book was published in installments from 1827 to 1838 (11 years); individual plates took far less time each.",
      "The prints are famously huge — Audubon used oversized \"double elephant folio\" paper so he could paint birds like herons and eagles life-size.",
      "April 26, 1785","Les Cayes, Saint-Domingue (present-day Haiti)","January 27, 1851","New York City, USA","G"],
    ["Self-Portrait in the Green Bugatti","Tamara de Lempicka",
      "No confirmed public auction record for this specific work, which is in a private collection; other de Lempicka paintings have sold at auction for over $20 million.",
      "Art Deco. Painted in 1929 (likely a few weeks).",
      "It began as a magazine cover commission — de Lempicka painted herself as a glamorous, independent woman behind the wheel of a car she didn't personally own, as a statement about modern femininity.",
      "May 16, 1894","Warsaw, Poland","March 18, 1980","Cuernavaca, Mexico","G"],
    ["Lady with an Ermine","Leonardo da Vinci",
      "Never sold on the open market — the Polish government acquired it from the Czartoryski family's foundation in 2016, in a deal reported at over $100 million for the whole collection.",
      "High Renaissance (early). Painted around 1489–1491 (about 2 years).",
      "The sitter, Cecilia Gallerani, was the teenage mistress of the Duke of Milan — and the ermine she holds is a symbol of purity that may also be a pun on the duke's nickname.",
      "April 15, 1452","Vinci, Republic of Florence","May 2, 1519","Amboise, France","G"],
    ["Violin and Candlestick","Georges Braque",
      "No confirmed public auction record — held at SFMOMA.",
      "Analytic Cubism. Painted around 1910 (a matter of months).",
      "Braque and Picasso developed Cubism together so closely around this time that paintings from this period are sometimes hard to tell apart without checking the signature.",
      "May 13, 1882","Argenteuil, France","August 31, 1963","Paris, France","G"],
    ["Still Life with Skull","Paul Cézanne",
      "No confirmed public auction record — held in a museum/private collection.",
      "Post-Impressionism. Painted sometime in the 1890s–1900s — Cézanne worked slowly and often returned to still lifes over months.",
      "Cézanne painted several skull still lifes late in life, using them the way earlier artists used a \"memento mori\" — a symbolic reminder of mortality.",
      "January 19, 1839","Aix-en-Provence, France","October 22, 1906","Aix-en-Provence, France","G"],
    ["Untitled, 1982","Jean-Michel Basquiat",
      "Sold at Sotheby's in 2017 for $110.5 million — a record for an American artist at the time. The same painting had sold for just $19,000 at auction in 1984.",
      "Neo-Expressionism. Painted in 1982 (likely just days — Basquiat worked fast).",
      "Basquiat was only 21 when he painted it — the same year he had six solo gallery shows and rocketed from graffiti artist to art-world star.",
      "December 22, 1960","Brooklyn, New York, USA","August 12, 1988","New York City, USA","G"],
    ["The Kiss","Francesco Hayez",
      "Never sold — held at the Pinacoteca di Brera in Milan since it was painted.",
      "Romanticism. Painted in 1859 (a matter of months).",
      "It's widely read as a symbol of Italian unification — the man's foot rests on a step in shadow, hinting that he may be about to leave for war.",
      "February 10, 1791","Venice, Italy","February 21, 1882","Milan, Italy","G"],
    ["Self-Portrait","Vincent Van Gogh",
      "No confirmed public auction record for this specific self-portrait — Van Gogh painted around 36 self-portraits, most now in museums.",
      "Post-Impressionism. Painted in the late 1880s, typically in a single sitting.",
      "Van Gogh painted so many self-portraits partly because he couldn't afford models — he was his own cheapest, most available subject.",
      "March 30, 1853","Groot-Zundert, Netherlands","July 29, 1890","Auvers-sur-Oise, France","O"],
    ["Composition 8","Wassily Kandinsky",
      "Never sold — part of the Guggenheim Museum's founding collection in New York.",
      "Bauhaus-era geometric abstraction. Painted in 1923 (likely a few weeks).",
      "Kandinsky taught at Germany's Bauhaus school when he painted this — full of circles, triangles, and grids reflecting the era's fascination with geometry and design theory.",
      "December 16, 1866","Moscow, Russia","December 13, 1944","Neuilly-sur-Seine, France","O"],
    ["The Angelus","Jean-François Millet",
      "Sold in 1889 for a then-record price after a bidding war between French and American buyers; later donated to the French state and now at the Musée d'Orsay.",
      "Realism (Barbizon School). Painted 1857–1859 (about 2 years).",
      "It shows two peasants pausing to pray at the evening church bell; Salvador Dalí became obsessed with the painting, wrongly convinced the basket between the figures once held a buried child's coffin.",
      "October 4, 1814","Gruchy, Normandy, France","January 20, 1875","Barbizon, France","O"],
    ["The Skiff","Pierre-Auguste Renoir",
      "No confirmed public auction record — held at the National Gallery, London.",
      "Impressionism. Painted around 1875, likely in a single outdoor session.",
      "It shows people boating on the Seine near Paris, a leisure activity the growing middle class loved and that Impressionist painters captured often.",
      "February 25, 1841","Limoges, France","December 3, 1919","Cagnes-sur-Mer, France","O"],
    ["The Milkmaid","Johannes Vermeer",
      "Never resold since the Rijksmuseum acquired it in 1908.",
      "Dutch Golden Age. Painted around 1658–1661 (about 3 years, though Vermeer worked on multiple pieces at once).",
      "Vermeer used natural ultramarine, made from crushed lapis lazuli and hugely expensive at the time, for the maid's apron — a costly choice for such an everyday subject.",
      "Baptized October 31, 1632 (exact birth date unrecorded)","Delft, Dutch Republic","December 15, 1675","Delft, Dutch Republic","O"],
    ["The Dance Class","Edgar Degas",
      "No confirmed public auction record for this version — versions of the subject are held at the Met and the Musée d'Orsay.",
      "Impressionism / Realism. Painted in the mid-1870s (likely a few months — Degas often reworked pieces over time).",
      "Degas attended real ballet rehearsals at the Paris Opéra to sketch dancers from life — he was more drawn to the tired, unglamorous moments between poses than the performances themselves.",
      "July 19, 1834","Paris, France","September 27, 1917","Paris, France","O"],
    ["The Gleaners","Jean-François Millet",
      "Never sold — donated to the French state in 1889 and now at the Musée d'Orsay.",
      "Realism (Barbizon School). Painted in 1857 (several months).",
      "It shows the poorest rural workers gathering leftover grain by hand; wealthy critics at the time were uneasy about Millet giving such dignified, monumental treatment to poor laborers.",
      "October 4, 1814","Gruchy, Normandy, France","January 20, 1875","Barbizon, France","O"],
    ["Madonna della Seggiola","Raphael",
      "Never sold — held at the Palazzo Pitti in Florence.",
      "High Renaissance. Painted around 1513–1514 (about a year).",
      "It's painted on a circular wood panel, called a \"tondo\" — a challenging format that forces the figures into a tightly interlocking, curved composition.",
      "c. April 6, 1483","Urbino, Italy","April 6, 1520","Rome, Papal States","O"],
    ["Breezing Up","Winslow Homer",
      "No confirmed public auction record — held at the National Gallery of Art, Washington, D.C.",
      "American Realism. Painted 1873–1876 (about 3 years — Homer reworked it repeatedly after it was first shown).",
      "Homer reworked the painting for years after it was first shown — X-rays have revealed a fourth figure in the boat that he later painted over.",
      "February 24, 1836","Boston, Massachusetts, USA","September 29, 1910","Prouts Neck, Maine, USA","O"],
    ["The Third of May","Francisco de Goya",
      "Never sold — commissioned by and remained with the Spanish state; now at the Museo del Prado.",
      "Romanticism. Painted in 1814 (a matter of months).",
      "Goya painted it six years after the mass execution of Spanish civilians it depicts — the glowing white shirt of the central figure has become one of art history's most famous symbols of martyrdom.",
      "March 30, 1746","Fuendetodos, Spain","April 16, 1828","Bordeaux, France","O"],
    ["Nafeaffaa Ipolpo (When Will You Marry)","Paul Gauguin",
      "Sold privately in 2015 to Qatar Museums for a reported $300 million — at the time, one of the highest prices ever paid for a painting.",
      "Post-Impressionism / Synthetism. Painted in 1892 (likely a few weeks, during Gauguin's prolific first Tahiti period).",
      "Gauguin painted it during his first trip to Tahiti, where he'd moved hoping to find a simpler life away from Europe.",
      "June 7, 1848","Paris, France","May 8, 1903","Atuona, Hiva Oa, French Polynesia","O"],
    ["Portrait of Dora Maar","Pablo Picasso",
      "Picasso painted many portraits of Dora Maar; some versions have sold at auction for tens of millions of dollars, including one for over $95 million in 2006.",
      "Cubism / Surrealism-adjacent. Painted around 1937 (likely just days — Picasso was extremely prolific during this period).",
      "Dora Maar was a photographer and artist in her own right, and Picasso's muse during the years he painted Guernica — she photographed its progress in his studio.",
      "October 25, 1881","Málaga, Spain","April 8, 1973","Mougins, France","O"],
    ["Interchange","Willem de Kooning",
      "Sold privately in 2015 for $300 million, one of the highest prices ever paid for a painting. De Kooning originally sold it in 1955 for just $4,000.",
      "Abstract Expressionism. Painted in 1955 (likely weeks — de Kooning often reworked paintings over time).",
      "The abstract swirl of color hides a barely visible seated woman near the center, a holdover from de Kooning's earlier, more figurative paintings of women.",
      "April 24, 1904","Rotterdam, Netherlands","March 19, 1997","East Hampton, New York, USA","O"],
    ["Card Players","Paul Cézanne",
      "Sold privately in 2011 to the royal family of Qatar for about $250 million — at the time, the highest price ever paid for a painting.",
      "Post-Impressionism. This smallest version was painted 1892–1893; the full five-painting series spanned about 1890–1896 (roughly 6 years).",
      "Cézanne made five versions of this scene, each simpler than the last, cutting the number of players from five down to two — the other four are all in major museums.",
      "January 19, 1839","Aix-en-Provence, France","October 22, 1906","Aix-en-Provence, France","O"],
    ["Shot Sage Blue Marilyn","Andy Warhol",
      "Sold at Christie's in 2022 for $195 million — the most expensive 20th-century artwork ever sold at auction, and the most ever paid for work by an American artist.",
      "Pop Art. Painted (silkscreened) in 1964, likely within days given Warhol's fast studio production methods.",
      "It's named for a real incident: a performance artist once fired a gun through a stack of Warhol's Marilyn canvases in his studio — though this particular blue version wasn't the one struck.",
      "August 6, 1928","Pittsburgh, Pennsylvania, USA","February 22, 1987","New York City, USA","O"]
  ];

  // Maps a "Title||Artist" key (matches buildItemKeyMap's convention,
  // since a couple of titles repeat across different artists) to a
  // preloaded image in images/, for the default set's out-of-the-box
  // experience. Entries without an image just have none until one is
  // uploaded (or added later).
  window.SEED_IMAGES = {
    "Mona Lisa||Leonardo da Vinci": "images/mona-lisa.jpg",
    "The Starry Night||Vincent Van Gogh": "images/the-starry-night.jpg",
    "Whistler's Mother||James McNeill Whistler": "images/whistlers-mother.jpg",
    "American Gothic||Grant Wood": "images/american-gothic.jpg",
    "The Scream||Edvard Munch": "images/the-scream.jpg",
    "The Creation of Adam||Michelangelo": "images/the-creation-of-adam.jpg",
    "The Persistence of Memory||Salvador Dalí": "images/the-persistence-of-memory.jpg",
    "Girl with a Pearl Earring||Johannes Vermeer": "images/girl-with-a-pearl-earring.jpg",
    "The Birth of Venus||Sandro Botticelli": "images/the-birth-of-venus.jpg",
    "The Night Watch||Rembrandt": "images/the-night-watch.jpg",
    "The Kiss||Gustav Klimt": "images/the-kiss.jpg",
    "The Garden of Earthly Delights||Hieronymus Bosch": "images/the-garden-of-earthly-delights.jpg",
    "Les Demoiselles d'Avignon||Pablo Picasso": "images/les-demoiselles-davignon.jpg",
    "The Last Supper||Leonardo da Vinci": "images/the-last-supper.jpg",
    "The Raft of the Medusa||Théodore Géricault": "images/the-raft-of-the-medusa.jpg",
    "The School of Athens||Raphael": "images/the-school-of-athens.jpg",
    "The Girl with a Balloon||Banksy": "images/the-girl-with-a-balloon.jpg",
    "The Great Wave off Kanagawa||Katsushika Hokusai": "images/the-great-wave-off-kanagawa.jpg",
    "Vase with Twelve Sunflowers||Vincent Van Gogh": "images/vase-with-twelve-sunflowers.jpg",
    "Tableau I||Piet Mondrian": "images/tableau-1.jpg",
    "Convergence||Jackson Pollock": "images/convergence.jpg",
    "Impression, Sunrise||Claude Monet": "images/impression-sunrise.jpg",
    "Woman with a Parasol — Madame Monet and Her Son||Claude Monet": "images/woman-with-a-parasol-madam-monet-and-son.jpg",
    "Broadway Boogie Woogie||Piet Mondrian": "images/broadway-boogie-woogie.jpg",
    "Composition VII||Wassily Kandinsky": "images/composition-VII.jpg",
    "Irises||Vincent Van Gogh": "images/irises.jpg",
    "Mother and Child||Mary Cassatt": "images/mother-and-child.jpg",
    "Flowers in a Crystal Vase||Édouard Manet": "images/flowers-in-a-crystał-vase.jpg",
    "Young Hare||Albrecht Dürer": "images/young-hare.jpg",
    "The Ancient of Days||William Blake": "images/the-ancient-of-days.jpg",
    "Self-Portrait with Thorn Necklace and Hummingbird||Frida Kahlo": "images/Self-Portrait-with-Thorn-Necklace-and-Hummingbird.jpg",
    "Three Musicians||Pablo Picasso": "images/Three-Musicians.jpg",
    "A Sunday Afternoon on the Island of La Grande Jatte||Georges Seurat": "images/A-Sunday-Afternoon-on-the-Island-of-La-Grande-Jatte.jpg",
    "Guernica||Pablo Picasso": "images/Guernica.jpg",
    "The Flower Carrier||Diego Rivera": "images/the-flower-carrier.jpg",
    "Water Lilies, Giverny #4||Claude Monet": "images/Water-Lilies-Giverny-4.jpg",
    "Café Terrace at Night||Vincent Van Gogh": "images/cafe-terrace-at-night.jpg",
    "The Son of Man||René Magritte": "images/son-of-man.jpg",
    "Bal du Moulin de la Galette||Pierre-Auguste Renoir": "images/Bal-du-Moulin-de-la-Galette.jpg",
    "Salvator Mundi||Leonardo da Vinci": "images/salvator-mundi.jpg",
    "Christina's World||Andrew Wyeth": "images/christinas-world.jpg",
    "The Painter of Sunflowers||Paul Gauguin": "images/the-painter-of-sunflowers.jpg",
    "Almond Blossom||Vincent Van Gogh": "images/almond-blossom.jpg",
    "The Sistine Chapel Ceiling||Michelangelo": "images/sisteen-chapel-ceiling.jpg",
    "The Arnolfini Portrait||Jan van Eyck": "images/the-arnolfini-portrait.jpg",
    "Las Meninas||Diego Velázquez": "images/las-meninas.jpg",
    "Luncheon of the Boating Party||Pierre-Auguste Renoir": "images/luncheon-of-the-boating-party.jpg",
    "Liberty Leading the People||Eugène Delacroix": "images/liberty-leading-the-people.jpg",
    "Napoleon Crossing the Alps||Jacques-Louis David": "images/napoleon-crossing-the-alps.jpg",
    "Self-Portrait||Vincent Van Gogh": "images/self-portrait-by-vincent-van-gogh.jpg",
    "Madonna della Seggiola||Raphael": "images/madonna-della-seggoila.png",
    "The Angelus||Jean-François Millet": "images/the-angelus.jpg",
    "The Dance Class||Edgar Degas": "images/the-dance-class.jpg",
    "The Gleaners||Jean-François Millet": "images/the-gleaners.jpg",
    "The Milkmaid||Johannes Vermeer": "images/the-milkmaid.jpg",
    "The Skiff||Pierre-Auguste Renoir": "images/the-skiff.jpg",
    "Composition 8||Wassily Kandinsky": "images/composition-8.jpg",
    "Still Life with Skull||Paul Cézanne": "images/still-life-with-skull.jpg",
    "The Kiss||Francesco Hayez": "images/the-kiss-by-hayez.jpg",
    "Untitled, 1982||Jean-Michel Basquiat": "images/untitled-1982.jpg",
    "Violin and Candlestick||Georges Braque": "images/violin-and-candlestick.jpg",
    "Self-Portrait in the Green Bugatti||Tamara de Lempicka": "images/Self-Portrait-in-the-Green-Bugatti.jpg",
    "Birds of America||John James Audubon": "images/birds-of-america-red-necked-grebe.jpg",
    "Lady with an Ermine||Leonardo da Vinci": "images/lady-with-an-ermine.jpg",
    "Looking Down Yosemite Valley||Albert Bierstadt": "images/looking-down-yosemite-valley.jpg",
    "Nighthawks||Edward Hopper": "images/nighthawks.jpg",
    "Deposition of Christ||Caravaggio": "images/Deposition-of-Christ.jpg",
    "The Sleeping Gypsy||Henri Rousseau": "images/the-sleeping-gypsy.jpg",
    "Breezing Up||Winslow Homer": "images/breezing-up.jpg",
    "The Third of May||Francisco de Goya": "images/the-third-of-may.jpg",
    "Nafeaffaa Ipolpo (When Will You Marry)||Paul Gauguin": "images/nafeaffaa-ipolpo.jpg",
    "Card Players||Paul Cézanne": "images/card-players.jpg",
    "Interchange||Willem de Kooning": "images/interchange.jpg",
    "Portrait of Dora Maar||Pablo Picasso": "images/portrait-of-dora.jpg",
    "Shot Sage Blue Marilyn||Andy Warhol": "images/shot-sage-blue-marilyn.jpg"
  };

  // Same "Title||Artist" keying, giving each seed item a clean display
  // date extracted from its Time Period fact text.
  window.SEED_DATES = {
    "Mona Lisa||Leonardo da Vinci": "1503–1517",
    "The Starry Night||Vincent Van Gogh": "1889",
    "Whistler's Mother||James McNeill Whistler": "1871",
    "American Gothic||Grant Wood": "1930",
    "The Scream||Edvard Munch": "1895",
    "The Creation of Adam||Michelangelo": "1508–1512",
    "The Persistence of Memory||Salvador Dalí": "1931",
    "Girl with a Pearl Earring||Johannes Vermeer": "1665",
    "The Birth of Venus||Sandro Botticelli": "1485",
    "The Night Watch||Rembrandt": "1642",
    "The Kiss||Gustav Klimt": "1907–1908",
    "The Garden of Earthly Delights||Hieronymus Bosch": "1490",
    "Les Demoiselles d'Avignon||Pablo Picasso": "1907",
    "The Last Supper||Leonardo da Vinci": "1495–1498",
    "The Raft of the Medusa||Théodore Géricault": "1818–1819",
    "The School of Athens||Raphael": "1509–1511",
    "The Girl with a Balloon||Banksy": "2002",
    "The Great Wave off Kanagawa||Katsushika Hokusai": "1831",
    "Vase with Twelve Sunflowers||Vincent Van Gogh": "1888",
    "Tableau I||Piet Mondrian": "1921",
    "Convergence||Jackson Pollock": "1952",
    "Impression, Sunrise||Claude Monet": "1872",
    "Woman with a Parasol — Madame Monet and Her Son||Claude Monet": "1875",
    "Broadway Boogie Woogie||Piet Mondrian": "1942–1943",
    "Composition VII||Wassily Kandinsky": "1913",
    "Irises||Vincent Van Gogh": "1889",
    "Mother and Child||Mary Cassatt": "1900",
    "Flowers in a Crystal Vase||Édouard Manet": "1880",
    "Young Hare||Albrecht Dürer": "1502",
    "The Ancient of Days||William Blake": "1794",
    "Self-Portrait with Thorn Necklace and Hummingbird||Frida Kahlo": "1940",
    "Three Musicians||Pablo Picasso": "1921",
    "A Sunday Afternoon on the Island of La Grande Jatte||Georges Seurat": "1884–1886",
    "Guernica||Pablo Picasso": "1937",
    "The Flower Carrier||Diego Rivera": "1935",
    "Water Lilies, Giverny #4||Claude Monet": "1900",
    "Café Terrace at Night||Vincent Van Gogh": "1888",
    "The Son of Man||René Magritte": "1964",
    "Bal du Moulin de la Galette||Pierre-Auguste Renoir": "1876",
    "Salvator Mundi||Leonardo da Vinci": "1500",
    "Christina's World||Andrew Wyeth": "1948",
    "The Painter of Sunflowers||Paul Gauguin": "1888",
    "Almond Blossom||Vincent Van Gogh": "1890",
    "The Sistine Chapel Ceiling||Michelangelo": "1508–1512",
    "The Arnolfini Portrait||Jan van Eyck": "1434",
    "Las Meninas||Diego Velázquez": "1656",
    "Luncheon of the Boating Party||Pierre-Auguste Renoir": "1880–1881",
    "Liberty Leading the People||Eugène Delacroix": "1830",
    "Napoleon Crossing the Alps||Jacques-Louis David": "1801–1805",
    "Deposition of Christ||Caravaggio": "1602–1603",
    "The Sleeping Gypsy||Henri Rousseau": "1897",
    "Nighthawks||Edward Hopper": "1941–1942",
    "Looking Down Yosemite Valley||Albert Bierstadt": "1860",
    "Birds of America||John James Audubon": "1827",
    "Self-Portrait in the Green Bugatti||Tamara de Lempicka": "1929",
    "Lady with an Ermine||Leonardo da Vinci": "1489–1491",
    "Violin and Candlestick||Georges Braque": "1910",
    "Still Life with Skull||Paul Cézanne": "1890",
    "Untitled, 1982||Jean-Michel Basquiat": "1982",
    "The Kiss||Francesco Hayez": "1859",
    "Self-Portrait||Vincent Van Gogh": "1880",
    "Composition 8||Wassily Kandinsky": "1923",
    "The Angelus||Jean-François Millet": "1857–1859",
    "The Skiff||Pierre-Auguste Renoir": "1875",
    "The Milkmaid||Johannes Vermeer": "1658–1661",
    "The Dance Class||Edgar Degas": "1870",
    "The Gleaners||Jean-François Millet": "1857",
    "Madonna della Seggiola||Raphael": "1513–1514",
    "Breezing Up||Winslow Homer": "1873–1876",
    "The Third of May||Francisco de Goya": "1814",
    "Nafeaffaa Ipolpo (When Will You Marry)||Paul Gauguin": "1892",
    "Portrait of Dora Maar||Pablo Picasso": "1937",
    "Interchange||Willem de Kooning": "1955",
    "Card Players||Paul Cézanne": "1892–1893",
    "Shot Sage Blue Marilyn||Andy Warhol": "1964"
  };

  window.SEED_MEDIUM = {
    "Mona Lisa||Leonardo da Vinci": "Oil on poplar panel",
    "The Starry Night||Vincent Van Gogh": "Oil on canvas",
    "Whistler's Mother||James McNeill Whistler": "Oil on canvas",
    "American Gothic||Grant Wood": "Oil on beaverboard",
    "The Scream||Edvard Munch": "Tempera and pastel on cardboard",
    "The Creation of Adam||Michelangelo": "Fresco on plaster ceiling",
    "The Persistence of Memory||Salvador Dalí": "Oil on canvas",
    "Girl with a Pearl Earring||Johannes Vermeer": "Oil on canvas",
    "The Birth of Venus||Sandro Botticelli": "Tempera on canvas",
    "The Night Watch||Rembrandt": "Oil on canvas",
    "The Kiss||Gustav Klimt": "Oil and gold leaf on canvas",
    "The Garden of Earthly Delights||Hieronymus Bosch": "Oil on oak panels",
    "Les Demoiselles d'Avignon||Pablo Picasso": "Oil on canvas",
    "The Last Supper||Leonardo da Vinci": "Tempera and oil on plaster",
    "The Raft of the Medusa||Théodore Géricault": "Oil on canvas",
    "The School of Athens||Raphael": "Fresco on plaster",
    "The Girl with a Balloon||Banksy": "Spray paint and acrylic on canvas",
    "The Great Wave off Kanagawa||Katsushika Hokusai": "Woodblock print on paper",
    "Vase with Twelve Sunflowers||Vincent Van Gogh": "Oil on canvas",
    "Tableau I||Piet Mondrian": "Oil on canvas",
    "Convergence||Jackson Pollock": "Oil on canvas",
    "Impression, Sunrise||Claude Monet": "Oil on canvas",
    "Woman with a Parasol — Madame Monet and Her Son||Claude Monet": "Oil on canvas",
    "Broadway Boogie Woogie||Piet Mondrian": "Oil on canvas",
    "Composition VII||Wassily Kandinsky": "Oil on canvas",
    "Irises||Vincent Van Gogh": "Oil on canvas",
    "Mother and Child||Mary Cassatt": "Oil on canvas",
    "Flowers in a Crystal Vase||Édouard Manet": "Oil on canvas",
    "Young Hare||Albrecht Dürer": "Watercolor and gouache on paper",
    "The Ancient of Days||William Blake": "Relief etching with watercolor on paper",
    "Self-Portrait with Thorn Necklace and Hummingbird||Frida Kahlo": "Oil on masonite",
    "Three Musicians||Pablo Picasso": "Oil on canvas",
    "A Sunday Afternoon on the Island of La Grande Jatte||Georges Seurat": "Oil on canvas",
    "Guernica||Pablo Picasso": "Oil on canvas",
    "The Flower Carrier||Diego Rivera": "Oil and tempera on masonite",
    "Water Lilies, Giverny #4||Claude Monet": "Oil on canvas",
    "Café Terrace at Night||Vincent Van Gogh": "Oil on canvas",
    "The Son of Man||René Magritte": "Oil on canvas",
    "Bal du Moulin de la Galette||Pierre-Auguste Renoir": "Oil on canvas",
    "Salvator Mundi||Leonardo da Vinci": "Oil on walnut panel",
    "Christina's World||Andrew Wyeth": "Tempera on gessoed panel",
    "The Painter of Sunflowers||Paul Gauguin": "Oil on canvas",
    "Almond Blossom||Vincent Van Gogh": "Oil on canvas",
    "The Sistine Chapel Ceiling||Michelangelo": "Fresco on plaster",
    "The Arnolfini Portrait||Jan van Eyck": "Oil on oak panel",
    "Las Meninas||Diego Velázquez": "Oil on canvas",
    "Luncheon of the Boating Party||Pierre-Auguste Renoir": "Oil on canvas",
    "Liberty Leading the People||Eugène Delacroix": "Oil on canvas",
    "Napoleon Crossing the Alps||Jacques-Louis David": "Oil on canvas",
    "Deposition of Christ||Caravaggio": "Oil on canvas",
    "The Sleeping Gypsy||Henri Rousseau": "Oil on canvas",
    "Nighthawks||Edward Hopper": "Oil on canvas",
    "Looking Down Yosemite Valley||Albert Bierstadt": "Oil on canvas",
    "Birds of America||John James Audubon": "Watercolor and gouache on paper",
    "Self-Portrait in the Green Bugatti||Tamara de Lempicka": "Oil on panel",
    "Lady with an Ermine||Leonardo da Vinci": "Oil on walnut panel",
    "Violin and Candlestick||Georges Braque": "Oil on canvas",
    "Still Life with Skull||Paul Cézanne": "Oil on canvas",
    "Untitled, 1982||Jean-Michel Basquiat": "Acrylic and oil stick on canvas",
    "The Kiss||Francesco Hayez": "Oil on canvas",
    "Self-Portrait||Vincent Van Gogh": "Oil on canvas",
    "Composition 8||Wassily Kandinsky": "Oil on canvas",
    "The Angelus||Jean-François Millet": "Oil on canvas",
    "The Skiff||Pierre-Auguste Renoir": "Oil on canvas",
    "The Milkmaid||Johannes Vermeer": "Oil on canvas",
    "The Dance Class||Edgar Degas": "Oil on canvas",
    "The Gleaners||Jean-François Millet": "Oil on canvas",
    "Madonna della Seggiola||Raphael": "Oil on panel",
    "Breezing Up||Winslow Homer": "Oil on canvas",
    "The Third of May||Francisco de Goya": "Oil on canvas",
    "Nafeaffaa Ipolpo (When Will You Marry)||Paul Gauguin": "Oil on canvas",
    "Portrait of Dora Maar||Pablo Picasso": "Oil on canvas",
    "Interchange||Willem de Kooning": "Oil on canvas",
    "Card Players||Paul Cézanne": "Oil on canvas",
    "Shot Sage Blue Marilyn||Andy Warhol": "Silkscreen ink on linen"
  };
